name: fastpicker
description: This is the official intuitive photo and video picker for FastAd. It supports multiple photos and videos selection on iOS and Android.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  photo_manager: ^3.0.0-dev.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

